import { useState } from 'react'
import { CheckCircle2, ChevronDown, Copy, Play, Rocket, Send, Sparkles, User } from 'lucide-react'

const GENERATED = `-- Generated by RealGraph Composer
-- Objective: governed vendor-comparison agent pipeline
DEFINE FUNCTION fn::run_vendor_pipeline($objective: record<objective>) {
  -- 1. Policy gate (must pass before any agent runs)
  LET $policy = fn::evaluate_policy($objective, "AGX-RUNTIME-DEFAULT");
  IF $policy.effect != "allow" { THROW "blocked by governance policy"; };

  -- 2. Plan -> research -> draft (agents propose, DB records)
  LET $plan     = fn::start_agent($objective, "planner");
  LET $research = fn::handoff($plan, "researcher", { scope: "vendor docs + pricing" });
  LET $draft    = fn::handoff($research, "writer", { artifact: "comparison_deck" });

  -- 3. Evaluate + trust gate before publish
  LET $eval  = fn::record_evaluation($draft.artifact, "CLEAR");
  LET $trust = fn::update_trust($draft.artifact);
  IF $eval.composite_score < 0.7 { THROW "failed CLEAR eval gate"; };

  RETURN { artifact: $draft.artifact, eval: $eval, trust: $trust };
};`

const SUMMARY = [
  'Adds a governance policy gate before any agent runs',
  'Wires planner → researcher → writer handoffs',
  'Records a CLEAR evaluation and trust update',
  'Blocks publish unless the eval gate passes',
]

const STEPS = [
  { agent: 'planner',    role: 'Plan',     detail: 'Decompose objective into research + drafting tasks' },
  { agent: 'researcher', role: 'Research', detail: 'Gather vendor docs + pricing within policy scope' },
  { agent: 'writer',     role: 'Draft',    detail: 'Produce comparison_deck artifact' },
  { agent: 'evaluator',  role: 'Evaluate', detail: 'CLEAR eval — gate at composite ≥ 0.70' },
  { agent: 'governor',   role: 'Trust',    detail: 'Update trust score, then publish' },
]

type Tab = 'compose' | 'preview' | 'deploy'

const TABS: { id: Tab; label: string }[] = [
  { id: 'compose', label: 'Compose' },
  { id: 'preview', label: 'Preview' },
  { id: 'deploy',  label: 'Deploy' },
]

export function ComposerView() {
  const [tab, setTab] = useState<Tab>('compose')
  const [open, setOpen] = useState(true)

  return (
    <div className="flex flex-col h-[calc(100vh-9.5rem)]">
      {/* Tab strip */}
      <div className="flex items-center justify-between mb-4">
        <div className="inline-flex items-center gap-1 rounded-lg border border-line bg-surface/60 p-1">
          {TABS.map(t => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={`px-3.5 py-1.5 rounded-md text-sm font-medium transition-all ${
                tab === t.id ? 'bg-raised text-ink shadow-sm ring-1 ring-line-strong' : 'text-muted hover:text-ink'
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>
        <div className="flex items-center gap-2 text-xs text-faint">
          <span className="inline-flex items-center gap-1.5 rounded-full border border-line bg-raised/60 px-2.5 py-1">
            <Sparkles size={12} className="text-accent" /> builder coworker
          </span>
        </div>
      </div>

      {tab === 'compose' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 flex-1 min-h-0">
          {/* Chat */}
          <div className="rounded-xl border border-line bg-raised/60 flex flex-col overflow-hidden">
            <div className="px-5 py-3 border-b border-line text-[11px] font-semibold uppercase tracking-[0.13em] text-muted">Conversation</div>
            <div className="flex-1 overflow-auto px-5 py-5 space-y-5">
              <div className="flex justify-end">
                <div className="max-w-[80%] rounded-2xl rounded-br-sm bg-accent-strong/90 text-white px-4 py-2.5 text-sm shadow-lg shadow-accent-strong/20">
                  Create a governed vendor-comparison agent pipeline that passes our policy and eval gates.
                </div>
              </div>
              <div className="flex gap-3">
                <div className="mt-0.5 w-7 h-7 shrink-0 rounded-lg bg-accent/12 text-accent ring-1 ring-accent/25 grid place-items-center">
                  <Sparkles size={14} />
                </div>
                <div className="min-w-0 flex-1 space-y-3">
                  <div className="rounded-2xl rounded-tl-sm border border-line bg-surface/70 px-4 py-3 text-sm text-ink">
                    On it — generating an AgentQL/SurrealQL pipeline from your spaces and governance policies.
                  </div>
                  <div className="rounded-xl border border-line bg-surface/50 overflow-hidden">
                    <button onClick={() => setOpen(o => !o)} className="w-full flex items-center gap-2 px-4 py-2.5 text-xs font-medium text-muted hover:text-ink transition-colors">
                      <ChevronDown size={14} className={`transition-transform ${open ? '' : '-rotate-90'}`} />
                      Thought process
                    </button>
                    {open && (
                      <ul className="px-4 pb-3 space-y-1.5">
                        {SUMMARY.map(s => (
                          <li key={s} className="flex items-start gap-2 text-xs text-muted">
                            <span className="mt-1.5 w-1 h-1 rounded-full bg-accent shrink-0" />{s}
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                  <p className="text-xs text-faint">Generated <span className="text-muted">fn::run_vendor_pipeline</span> → preview on the right. Let me know if you want changes.</p>
                </div>
              </div>
            </div>
            <div className="px-4 py-3 border-t border-line">
              <div className="flex items-center gap-2 rounded-lg border border-line bg-field/70 px-3 py-2 focus-within:border-accent transition-colors">
                <User size={14} className="text-faint" />
                <input placeholder="Describe the agent pipeline to build…" className="flex-1 bg-transparent text-sm text-ink placeholder:text-faint focus:outline-none" />
                <button className="text-accent hover:text-ink transition-colors"><Send size={15} /></button>
              </div>
            </div>
          </div>

          {/* Code panel */}
          <div className="glow-border bg-[#0b0f17] flex flex-col overflow-hidden">
            <div className="px-4 py-2.5 border-b border-line flex items-center justify-between">
              <div className="flex items-center gap-2 text-xs">
                <span className="w-2.5 h-2.5 rounded-full bg-bad/70" />
                <span className="w-2.5 h-2.5 rounded-full bg-warn/70" />
                <span className="w-2.5 h-2.5 rounded-full bg-ok/70" />
                <span className="ml-2 text-muted font-mono">vendor_pipeline.surql</span>
              </div>
              <div className="flex items-center gap-1.5">
                <button className="inline-flex items-center gap-1 text-[11px] text-muted hover:text-ink rounded-md px-2 py-1 hover:bg-raised transition-colors"><Copy size={12} /> Copy</button>
                <button className="inline-flex items-center gap-1 text-[11px] text-white rounded-md px-2 py-1 bg-accent-strong hover:bg-accent transition-colors"><Play size={12} /> Apply</button>
              </div>
            </div>
            <pre className="flex-1 overflow-auto text-[12.5px] leading-relaxed font-mono p-4">
              <code>
                {GENERATED.split('\n').map((line, i) => (
                  <div key={i} className="grid grid-cols-[2.5rem_1fr]">
                    <span className="text-right pr-4 text-faint/60 select-none nums">{i + 1}</span>
                    <span className={
                      line.trim().startsWith('--') ? 'text-faint'
                      : line.includes('THROW') ? 'text-bad'
                      : line.includes('DEFINE') || line.includes('RETURN') || line.includes('LET') || line.includes('IF') ? 'text-accent'
                      : 'text-ink'
                    }>{line || ' '}</span>
                  </div>
                ))}
              </code>
            </pre>
          </div>
        </div>
      )}

      {tab === 'preview' && (
        <div className="flex-1 min-h-0 overflow-auto">
          <div className="rounded-xl border border-line bg-raised/40 p-6 max-w-3xl">
            <div className="text-sm font-medium text-ink mb-1">Pipeline preview</div>
            <p className="text-xs text-faint mb-5">Dry-run of <span className="font-mono text-muted">fn::run_vendor_pipeline</span> — agents propose, the database records, gates enforce.</p>
            <ol className="relative border-l border-line ml-3 space-y-5">
              {STEPS.map((s, i) => (
                <li key={s.agent} className="ml-6">
                  <span className="absolute -left-[9px] grid place-items-center w-[18px] h-[18px] rounded-full bg-accent/15 ring-1 ring-accent/30 text-accent text-[10px] font-semibold">{i + 1}</span>
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-ink">{s.role}</span>
                    <span className="text-[11px] font-mono text-accent bg-accent/10 rounded px-1.5 py-0.5">{s.agent}</span>
                  </div>
                  <p className="text-xs text-faint mt-0.5">{s.detail}</p>
                </li>
              ))}
            </ol>
            <div className="mt-6 flex items-center gap-2 text-xs text-ok">
              <CheckCircle2 size={14} /> Passes policy gate · CLEAR eval gate · trust ≥ threshold
            </div>
          </div>
        </div>
      )}

      {tab === 'deploy' && (
        <div className="flex-1 min-h-0 overflow-auto">
          <div className="rounded-xl border border-line bg-raised/40 p-6 max-w-2xl space-y-5">
            <div>
              <div className="text-sm font-medium text-ink mb-1">Deploy pipeline</div>
              <p className="text-xs text-faint">Publish <span className="font-mono text-muted">fn::run_vendor_pipeline</span> as a callable agent endpoint.</p>
            </div>
            <div className="grid grid-cols-2 gap-3">
              {[
                { k: 'Endpoint', v: 'POST /agents/vendor-pipeline' },
                { k: 'Runtime',  v: 'SurrealDB function' },
                { k: 'Guardrails', v: 'policy + CLEAR + trust' },
                { k: 'Status',   v: 'draft' },
              ].map(f => (
                <div key={f.k} className="rounded-lg border border-line bg-surface/50 px-3.5 py-2.5">
                  <div className="text-[11px] text-faint">{f.k}</div>
                  <div className="text-sm text-ink font-mono mt-0.5">{f.v}</div>
                </div>
              ))}
            </div>
            <button className="inline-flex items-center gap-2 rounded-lg bg-accent-strong hover:bg-accent text-white text-sm font-medium px-4 py-2 transition-colors">
              <Rocket size={15} /> Deploy to workspace
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
