import { useState } from 'react'
import { ChevronDown, Copy, Play, Send, Sparkles, User } from 'lucide-react'

const GENERATED = `-- Generated by RealGraph Composer
-- Objective: governed vendor-comparison agent pipeline
DEFINE FUNCTION fn::run_vendor_pipeline($objective: record<objective>) {
  -- 1. Policy gate (must pass before any agent runs)
  LET $policy = fn::evaluate_policy($objective, "AGX-RUNTIME-DEFAULT");
  IF $policy.effect != "allow" { THROW "blocked by governance policy"; };

  -- 2. Plan -> research -> draft (agents propose, DB records)
  LET $plan     = fn::start_agent($objective, "planner");
  LET $research = fn::handoff($plan, "researcher", { scope: "vendor docs + pricing" });
  LET $draft    = fn::handoff($research, "writer", { artifact: "comparison_deck" });

  -- 3. Evaluate + trust gate before publish
  LET $eval  = fn::record_evaluation($draft.artifact, "CLEAR");
  LET $trust = fn::update_trust($draft.artifact);
  IF $eval.composite_score < 0.7 { THROW "failed CLEAR eval gate"; };

  RETURN { artifact: $draft.artifact, eval: $eval, trust: $trust };
};`

const SUMMARY = [
  'Adds a governance policy gate before any agent runs',
  'Wires planner → researcher → writer handoffs',
  'Records a CLEAR evaluation and trust update',
  'Blocks publish unless the eval gate passes',
]

export function ComposerView() {
  const [open, setOpen] = useState(true)

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 h-[calc(100vh-9.5rem)]">
      {/* Chat */}
      <div className="rounded-xl border border-line bg-raised/60 flex flex-col overflow-hidden">
        <div className="px-5 py-3 border-b border-line text-[11px] font-semibold uppercase tracking-[0.13em] text-muted">Composer</div>
        <div className="flex-1 overflow-auto px-5 py-5 space-y-5">
          {/* user */}
          <div className="flex justify-end">
            <div className="max-w-[80%] rounded-2xl rounded-br-sm bg-accent-strong/90 text-white px-4 py-2.5 text-sm shadow-lg shadow-accent-strong/20">
              Create a governed vendor-comparison agent pipeline that passes our policy and eval gates.
            </div>
          </div>
          {/* agent */}
          <div className="flex gap-3">
            <div className="mt-0.5 w-7 h-7 shrink-0 rounded-lg bg-accent/12 text-accent ring-1 ring-accent/25 grid place-items-center">
              <Sparkles size={14} />
            </div>
            <div className="min-w-0 flex-1 space-y-3">
              <div className="rounded-2xl rounded-tl-sm border border-line bg-surface/70 px-4 py-3 text-sm text-ink">
                On it — generating an AgentQL/SurrealQL pipeline from your spaces and governance policies.
              </div>
              <div className="rounded-xl border border-line bg-surface/50 overflow-hidden">
                <button onClick={() => setOpen(o => !o)} className="w-full flex items-center gap-2 px-4 py-2.5 text-xs font-medium text-muted hover:text-ink transition-colors">
                  <ChevronDown size={14} className={`transition-transform ${open ? '' : '-rotate-90'}`} />
                  Thought process
                </button>
                {open && (
                  <ul className="px-4 pb-3 space-y-1.5">
                    {SUMMARY.map(s => (
                      <li key={s} className="flex items-start gap-2 text-xs text-muted">
                        <span className="mt-1.5 w-1 h-1 rounded-full bg-accent shrink-0" />{s}
                      </li>
                    ))}
                  </ul>
                )}
              </div>
              <p className="text-xs text-faint">Generated <span className="text-muted">fn::run_vendor_pipeline</span> → preview on the right. Let me know if you want changes.</p>
            </div>
          </div>
        </div>
        <div className="px-4 py-3 border-t border-line">
          <div className="flex items-center gap-2 rounded-lg border border-line bg-field/70 px-3 py-2 focus-within:border-accent transition-colors">
            <User size={14} className="text-faint" />
            <input placeholder="Describe the agent pipeline to build…" className="flex-1 bg-transparent text-sm text-ink placeholder:text-faint focus:outline-none" />
            <button className="text-accent hover:text-ink transition-colors"><Send size={15} /></button>
          </div>
        </div>
      </div>

      {/* Code panel */}
      <div className="rounded-xl border border-line bg-[#0b0f17] flex flex-col overflow-hidden">
        <div className="px-4 py-2.5 border-b border-line flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs">
            <span className="w-2.5 h-2.5 rounded-full bg-bad/70" />
            <span className="w-2.5 h-2.5 rounded-full bg-warn/70" />
            <span className="w-2.5 h-2.5 rounded-full bg-ok/70" />
            <span className="ml-2 text-muted font-mono">vendor_pipeline.surql</span>
          </div>
          <div className="flex items-center gap-1.5">
            <button className="inline-flex items-center gap-1 text-[11px] text-muted hover:text-ink rounded-md px-2 py-1 hover:bg-raised transition-colors"><Copy size={12} /> Copy</button>
            <button className="inline-flex items-center gap-1 text-[11px] text-white rounded-md px-2 py-1 bg-accent-strong hover:bg-accent transition-colors"><Play size={12} /> Apply</button>
          </div>
        </div>
        <pre className="flex-1 overflow-auto text-[12.5px] leading-relaxed font-mono p-4">
          <code>
            {GENERATED.split('\n').map((line, i) => (
              <div key={i} className="grid grid-cols-[2.5rem_1fr]">
                <span className="text-right pr-4 text-faint/60 select-none nums">{i + 1}</span>
                <span className={
                  line.trim().startsWith('--') ? 'text-faint'
                  : line.includes('THROW') ? 'text-bad'
                  : line.includes('DEFINE') || line.includes('RETURN') || line.includes('LET') || line.includes('IF') ? 'text-accent'
                  : 'text-ink'
                }>{line || ' '}</span>
              </div>
            ))}
          </code>
        </pre>
      </div>
    </div>
  )
}
