apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: realgraph

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - surrealdb.yaml
  - minio.yaml
  - agent-knowledge.yaml
  - agent-dashboard.yaml
  - ingress.yaml
  - letsencrypt-issuer.yaml
