apiVersion: v1
kind: Secret
metadata:
  name: autonomyx-controller-webhook-tls
  namespace: autonomyx-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
    REPLACE_WITH_WEBHOOK_CERTIFICATE
  tls.key: |
    REPLACE_WITH_WEBHOOK_PRIVATE_KEY
