apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: realgraph-staging

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /data/PLATFORM_ENV
        value: staging
    target:
      kind: ConfigMap
      name: platform-config

  # Staging: 2 replicas, letsencrypt-staging issuer
  - patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging
    target:
      kind: Ingress
      name: realgraph-ingress
